-- Apaga as tabelas caso existam
DROP TABLE IF EXISTS ITENS;
DROP TABLE IF EXISTS JOGOS_USUARIOS;
DROP TABLE IF EXISTS JOGOS;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TOTAL_JOGADOR;

-- Criando tabelas
-- CREATE TABLE NOME ( CAMPOS );
CREATE TABLE USUARIOS (
  ID_USUARIO SERIAL PRIMARY KEY,
  USUARIO VARCHAR(10) NOT NULL,
  SENHA VARCHAR(20) NOT NULL,
  NOME VARCHAR(40)
);

CREATE TABLE JOGOS (
   ID_JOGO SERIAL PRIMARY KEY,
   NOME VARCHAR(40),
   PRECO NUMERIC(12, 2)
);

CREATE TABLE JOGOS_USUARIOS (
    ID_JOGO_USUARIO SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_JOGO INT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO), -- ON DELETE CASCADE ( Caso queira que apage automaticamente )
    FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(ID_JOGO)
);

CREATE TABLE ITENS (
   ID_ITEM SERIAL PRIMARY KEY,
   ID_JOGO_USUARIO INT NOT NULL,
   DESCRICAO VARCHAR(20),
   QUANTIDADE INT,
   FOREIGN KEY (ID_JOGO_USUARIO) REFERENCES JOGOS_USUARIOS(ID_JOGO_USUARIO)
);


CREATE TABLE TOTAL_JOGADOR (
       ID_TOTAL_JOGADOR SERIAL PRIMARY KEY,
       ID_USUARIO INT NOT NULL,
       TOTAL NUMERIC(12,2),
       FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);
alter table TOTAL_JOGADOR add constraint unique_total_usuario UNIQUE(ID_USUARIO);

-- Adicionando ou removendo campos da tabela
-- ALTER TABLE USUARIOS ADD COLUNA TIPO; // Adicionar uma coluna
-- ALTER TABLE USUARIOS DROP COLUNA; // Apagar uma coluna
ALTER TABLE USUARIOS ADD PAIS VARCHAR(10);

-- Cria as constraints
alter table USUARIOS add constraint unique_usuario UNIQUE(USUARIO);
-- Constrains composta
-- alter table USUARIOS add constraint unique_usuario_senha UNIQUE(USUARIO, SENHA);